### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by maxclax** [Annixa/docker-pg_dump#4]
Job started: Mon Dec 25 21:09:26 UTC 2017
pg_dump: server version: 10.1; pg_dump version: 9.6.3
pg_dump: aborting because of server version mismatch

**Comment by maxclax** [comment]
I can't understand why in docker file use postgres:latest but in container pg_dump = 9.6.3 in new version more 10. Why?

**Comment by vingrad** [comment]
I have the same issue. @qari Did you find the solution?

**Comment by vingrad** [comment]
You can make your own image with docker build, but modify the "from line" to:
> FROM postgres:10.2

**Comment by cfairweather** [comment]
The Dockerfile doesn’t necessarily need to be modified; the image needs to be rebuilt. When the image was built a while ago, the latest postgres _was_ 9.6.3. 

This is one of the docker fundamentals you might acquaint yourself with.
